CREATE TABLE IF NOT EXISTS students
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    furigana VARCHAR(50),
    nickname VARCHAR(50),
    region VARCHAR(20),
    age INT,
    gender VARCHAR(5),
    remark VARCHAR(255),
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS students_courses
 (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    course_name VARCHAR(30) NOT NULL,
    course_start_at DATE,
    course_end_at DATE
);